/*
 * slave_RF_setting.c
 *
 * Created: 30/08/2023
 * Author : Andres Mezquida
 */

#include "gateway.h"
#include "slave_RF_operation.h"
#include "slave_RF_setting.h"

 char cmt2300_init_OK = FALSE;

void control_bank_1_set();

/*
 * Configura los registros del chip CMT2300A.
 */
void init_cmt2300a(){
	
	unsigned char reg_tmp;
	
	soft_reset();	// CMT2300AW soft reset.
	go_stby();		// Send the go_stby command and confirm that the chip is in the STBY state.
	
	/* Write the register contents generated by RFPDK to the configuration bank. */
    marco_escritura_banco(CMT_BANK_ADDR       , rfpdk_cmt_bank       , CMT_BANK_SIZE       );
    marco_escritura_banco(SYSTEM_BANK_ADDR    , rfpdk_system_bank    , SYSTEM_BANK_SIZE    );
    marco_escritura_banco(FREQUENCY_BANK_ADDR , rfpdk_frequency_bank , FREQUENCY_BANK_SIZE );
    marco_escritura_banco(DATA_RATE_BANK_ADDR , rfpdk_data_rate_bank  , DATA_RATE_BANK_SIZE);
    marco_escritura_banco(BASEBAND_BANK_ADDR  , rfpdk_baseband_bank  , BASEBAND_BANK_SIZE  );
    marco_escritura_banco(TX_BANK_ADDR        , rfpdk_tx_bank        , TX_BANK_SIZE        );
	
	/* If the user does not need to use SLEEP TIMER, disable LFOSC in syste bank */
	marco_lectura_registros(CUS_SYS2, &reg_tmp);
	
	reg_tmp &= ~MASK_LFOSC_RECAL_EN;
	reg_tmp &= ~MASK_LFOSC_CAL1_EN;
	reg_tmp &= ~MASK_LFOSC_CAL2_EN;
	marco_escritura_registros(CUS_SYS2, reg_tmp);
	
 	marco_lectura_registros(CUS_CMT10, &reg_tmp);
 	reg_tmp &= (~0x07);
 	marco_escritura_registros(CUS_CMT10, reg_tmp | 0x02);	// xosc_aac_code[2:0] = 2
	       	    
	/* Set RF Performance Mode according to constant applicability */
	marco_lectura_registros(CUS_SYS1, &reg_tmp);
	
	reg_tmp &= ~MASK_LMT_VTR;
	reg_tmp &= ~MASK_MIXER_BIAS;
	reg_tmp &= ~MASK_LNA_MODE;
	reg_tmp &= ~MASK_LNA_BIAS;	// clean
#ifdef LOW____RF_Performance
	reg_tmp |= ((0x2 << 6) | (0x2 << 4) | (0x1 << 2) | (0x1 << 0));  // set
#else
 #ifdef MEDIUM_RF_Performance
	reg_tmp |= ((0x2 << 6) | (0x2 << 4) | (0x1 << 2) | (0x2 << 0));  // set
 #else
  #ifdef HIGH___RF_Performance
	reg_tmp |= ((0x1 << 6) | (0x2 << 4) | (0x3 << 2) | (0x2 << 0));  // set
  #else
   #error "Undefined RF Performance"
  #endif // HIGH___RF_Performance
 #endif // MEDIUM_RF_Performance
#endif // LOW____RF_Performance
	
	marco_escritura_registros(CUS_SYS1, reg_tmp);
	       	    	 
	/* Set Packet Type according to constant applicability */
	marco_lectura_registros(CUS_PKT1, &reg_tmp);
 	
 	reg_tmp &= ~MASK_DATA_MODE; // clean
 	reg_tmp |= (DATA_MODE_VALUE << 0);  // set
 	marco_escritura_registros(CUS_PKT1, reg_tmp);

	/* Set Packet length type according to constant applicability */
	marco_lectura_registros(CUS_PKT14, &reg_tmp);
	
	reg_tmp &= ~MASK_PKT_TYPE; // clean
	reg_tmp |= (PKT_TYPE_VALUE << 0);  // set
	marco_escritura_registros(CUS_PKT14, reg_tmp);
	 
	/* Set Payload Length according to constant applicability */
	marco_escritura_registros(CUS_PKT15, (PAYLOAD_LENG_VALUE - 1));
	
	/* Set Preamble Rx Size according to constant applicability */
	marco_lectura_registros(CUS_PKT1, &reg_tmp);
	
	reg_tmp &= ~MASK_RX_PREAM_SIZE; // clean
	reg_tmp |= (RX_PREAM_SIZE_VALUE << 3);  // set
	marco_escritura_registros(CUS_PKT1, reg_tmp);
	  
	/* Set Preamble Tx Size according to constant applicability */
	marco_lectura_registros(CUS_PKT2, &reg_tmp);
	
	reg_tmp &= ~((unsigned int) MASK_TX_PREAM_SIZE_7_0); // clean
	reg_tmp |= (TX_PREAM_SIZE_VALUE >> 0);  // set
	marco_escritura_registros(CUS_PKT2, reg_tmp);
	
	marco_lectura_registros(CUS_PKT3, &reg_tmp);
	
	reg_tmp &= ~((unsigned int) MASK_TX_PREAM_SIZE_15_8); // clean
	reg_tmp |= (TX_PREAM_SIZE_VALUE >> 8);  // set
	marco_escritura_registros(CUS_PKT3, reg_tmp);
	   
	/* Set Preamble Unit according to constant applicability */
	marco_lectura_registros(CUS_PKT1, &reg_tmp);
	
	reg_tmp &= ~MASK_PREAM_LENG_UNIT; // clean
	reg_tmp |= (PREAM_LENG_UNIT_VALUE << 2);  // set
	marco_escritura_registros(CUS_PKT1, reg_tmp);
	    
	/* Set Preamble Value according to constant applicability */
	marco_escritura_registros(CUS_PKT4, PREAM_VALUE_VALUE);
	    
	/* Set Sync Size according to constant applicability */
	marco_lectura_registros(CUS_PKT5, &reg_tmp);
	
	reg_tmp &= ~MASK_SYNC_SIZE; // clean
	reg_tmp |= (SYNC_SIZE_VALUE << 1);  // set
	marco_escritura_registros(CUS_PKT5, reg_tmp);
	    
	/* Set Sync Value according to constant applicability */
	marco_lectura_registros(CUS_PKT6, &reg_tmp);
	
	reg_tmp &= ~((unsigned int) MASK_SYNC_VALUE_7_0); // clean
	reg_tmp |= (((long long) SYNC_VALUE_VALUE << (8*(8-SYNC_SIZE_VALUE))) >> 0);  // set
	marco_escritura_registros(CUS_PKT6, reg_tmp);

	marco_lectura_registros(CUS_PKT7, &reg_tmp);

	reg_tmp &= ~((unsigned int) MASK_SYNC_VALUE_15_8); // clean
	reg_tmp |= (((long long) SYNC_VALUE_VALUE << (8*(8-SYNC_SIZE_VALUE))) >> 8);  // set
	marco_escritura_registros(CUS_PKT7, reg_tmp);

	marco_lectura_registros(CUS_PKT8, &reg_tmp);

	reg_tmp &= ~((unsigned int) MASK_SYNC_VALUE_23_16); // clean
	reg_tmp |= (((long long) SYNC_VALUE_VALUE << (8*(8-SYNC_SIZE_VALUE))) >> 26);  // set
	marco_escritura_registros(CUS_PKT8, reg_tmp);

	marco_lectura_registros(CUS_PKT9, &reg_tmp);

	reg_tmp &= ~((unsigned int) MASK_SYNC_VALUE_31_24); // clean
	reg_tmp |= (((long long) SYNC_VALUE_VALUE << (8*(8-SYNC_SIZE_VALUE))) >> 24);  // set
	marco_escritura_registros(CUS_PKT9, reg_tmp);

	marco_lectura_registros(CUS_PKT10, &reg_tmp);

	reg_tmp &= ~((unsigned int) MASK_SYNC_VALUE_39_32); // clean
	reg_tmp |= (((long long) SYNC_VALUE_VALUE << (8*(8-SYNC_SIZE_VALUE))) >> 32);  // set
	marco_escritura_registros(CUS_PKT10, reg_tmp);

	marco_lectura_registros(CUS_PKT11, &reg_tmp);

	reg_tmp &= ~((unsigned int) MASK_SYNC_VALUE_47_40); // clean
	reg_tmp |= (((long long) SYNC_VALUE_VALUE << (8*(8-SYNC_SIZE_VALUE))) >> 40);  // set
	marco_escritura_registros(CUS_PKT11, reg_tmp);

	marco_lectura_registros(CUS_PKT12, &reg_tmp);

	reg_tmp &= ~((unsigned int) MASK_SYNC_VALUE_55_48); // clean
	reg_tmp |= (((long long) SYNC_VALUE_VALUE << (8*(8-SYNC_SIZE_VALUE))) >> 48);  // set
	marco_escritura_registros(CUS_PKT12, reg_tmp);

	marco_lectura_registros(CUS_PKT13, &reg_tmp);

	reg_tmp &= ~((unsigned int) MASK_SYNC_VALUE_63_56); // clean
	reg_tmp |= (((long long) SYNC_VALUE_VALUE << (8*(8-SYNC_SIZE_VALUE))) >> 56);  // set
	marco_escritura_registros(CUS_PKT13, reg_tmp);
		    
	/* Set CRC Option according to constant applicability */
	marco_lectura_registros(CUS_PKT21, &reg_tmp);
	
	reg_tmp &= ~MASK_CRC_TYPE; // clean
	reg_tmp |= (CRC_TYPE_VALUE << 1);  // set
	marco_escritura_registros(CUS_PKT21, reg_tmp);
	    	    
	/* Set CRC Seed according to constant applicability */
	marco_lectura_registros(CUS_PKT22, &reg_tmp);

	reg_tmp &= ~((unsigned int) MASK_CRC_SEED_7_0); // clean
	reg_tmp |= (CRC_SEED_VALUE >> 0);  // set
	marco_escritura_registros(CUS_PKT22, reg_tmp);

	marco_lectura_registros(CUS_PKT23, &reg_tmp);

	reg_tmp &= ~((unsigned int) MASK_CRC_SEED_15_8); // clean
	reg_tmp |= (CRC_SEED_VALUE >> 8);  // set
	marco_escritura_registros(CUS_PKT23, reg_tmp);
	       	    
	/* Set RSSI Detect Mode according to constant applicability */
	marco_lectura_registros(CUS_SYS11, &reg_tmp);
	
	reg_tmp &= ~MASK_RSSI_DET_SEL; // clean
	reg_tmp |= (RSSI_DET_SEL_VALUE << 3);  // set
	marco_escritura_registros(CUS_SYS11, reg_tmp);
	       	        	    
	/* Set RSSI Filter Setting according to constant applicability */
	marco_lectura_registros(CUS_SYS11, &reg_tmp);
	
	reg_tmp &= ~MASK_RSSI_AVG_MODE; // clean
	reg_tmp |= (RSSI_AVG_MODE_VALUE << 0);  // set
	marco_escritura_registros(CUS_SYS11, reg_tmp);
	       	        	        	    
	/* Set RSSI Valid Source according to constant applicability */
	marco_lectura_registros(CUS_SYS11, &reg_tmp);
	
	reg_tmp &= ~MASK_CCA_INT_SEL; // clean
	reg_tmp |= (CCA_INT_SEL_VALUE << 5);  // set
	marco_escritura_registros(CUS_SYS11, reg_tmp);
	       	        	        	        	    
	/* Set PJD Window according to constant applicability */
	marco_lectura_registros(CUS_SYS12, &reg_tmp);
	
	reg_tmp &= (~MASK_PJD_WIN_SEL); // clean
	reg_tmp |= (PJD_WIN_SEL_VALUE << 6);  // set
	marco_escritura_registros(CUS_SYS12, reg_tmp);
	       	        	        	        	     	    	    	
	control_bank_1_set(); // Control Bank 1 application set
	
	go_sleep(); // Send the go_sleep command for configuration to take effect.

	cmt2300_init_OK = TRUE;

}

/*
 * ...
 */
void control_bank_1_set(){
	
	unsigned char reg_tmp;

	// Enable CFG_RETAIN and disable RSTN_IN
	marco_lectura_registros(CUS_MODE_STA, &reg_tmp);
	
	reg_tmp |=  MASK_CFG_RETAIN;
	reg_tmp &= ~MASK_RSTN_IN_EN;
	marco_escritura_registros(CUS_MODE_STA, reg_tmp);
	
	marco_lectura_registros(CUS_EN_CTL, &reg_tmp);
	
	reg_tmp |= MASK_LOCKING_EN; // Enable LOCKING_EN
	marco_escritura_registros(CUS_EN_CTL, reg_tmp);
	
	//Enable antenna switch, output TX_ACTIVE/RX_ACTIVE via GPIO1/GPIO2.
	marco_lectura_registros(CUS_INT1_CTL, &reg_tmp);
	
	reg_tmp |=  MASK_RF_SWT2_EN;
	reg_tmp &= ~MASK_RF_SWT1_EN;
	marco_escritura_registros(CUS_INT1_CTL, reg_tmp);

	// Config INT2 > GPIO3
	// When enabling antenna switching, GPIO1/GPIO2 output RX_ACTIVE/TX_ACTIVE,
	// and it can't output INT1/INT2 via GPIO1/GPIO2
	marco_escritura_registros(CUS_IO_SEL, GPIO3_SEL_INT2);
	
	// Config interrupt INT2
	marco_lectura_registros(CUS_INT2_CTL, &reg_tmp);
		
	reg_tmp &= (~MASK_INT2_SEL); // clean INT2_SEL
	reg_tmp |= INT_SEL_RSSI_VLD;  // set INT2_SEL
	marco_escritura_registros(CUS_INT2_CTL, reg_tmp);
	
	// Enable interrupt
	// When enabling antenna switching, GPIO1/GPIO2 output RX_ACTIVE/TX_ACTIVE,
	// and it can't output INT1/INT2 via GPIO1/GPIO2
 	marco_escritura_registros(CUS_INT_EN,
 								/*MASK_SL_TMO_EN   |*/	// Sleep timeout interrupt enable
 								/*MASK_RX_TMO_EN   |*/	// Receiving timeout interrupt enable
 								MASK_TX_DONE_EN  |	// Transmitting done interrupt enable
 								MASK_PREAM_OK_EN |	// Preamble detection OK interrupt enable
 								MASK_SYNC_OK_EN  |	// Sync Word detection OK interrupt enable
 								/*MASK_NODE_OK_EN  |*/	// Node ID detection OK interrupt enable
 								MASK_CRC_OK_EN   |	// CRC detection OK interrupt enable
 								MASK_PKT_DONE_EN);	// Packet receiving done (Right or wrong)
								

	// Use a single 64-byte FIFO for either Tx or Rx
 	marco_lectura_registros(CUS_FIFO_CTL, &reg_tmp);
#if FIFO_LENG == 64
 	reg_tmp |= MASK_FIFO_MERGE_EN;
#else
	reg_tmp &= (~MASK_FIFO_MERGE_EN);
#endif
 	marco_escritura_registros(CUS_FIFO_CTL, reg_tmp);
}

/*
 * Imprime en el monitor serial la configuración actual de todos los registros.
 */
#if PRUEBA_CMT2300A == 1
void prueba_cmt2300a(){
	
	char string[256];
	//------------------ 
	unsigned char data_buff = 0;
	unsigned long data_buff_long = 0;
	
	serialUSB_Ready_link(TRUE);
	
	/* System Bank */
	serialUSB_print_link("\n\n::: System Bank :::\n\n");

	marco_lectura_registros(CUS_SYS11, &data_buff);
 	sprintf(string, "CUS_SYS11 = 0x%X" 
					"\t PJD_TH_SEL %d"
					"\t CCA_INT_SEL %d"
					"\t RSSI_DET_SEL %d"
					"\t RSSI_AVG_MODE %d"
					"\n\n", data_buff, (data_buff & MASK_PJD_TH_SEL)>>7, (data_buff & MASK_CCA_INT_SEL)>>5, (data_buff & MASK_RSSI_DET_SEL)>>3, (data_buff & MASK_RSSI_AVG_MODE));
 	serialUSB_print_link(string);

	marco_lectura_registros(CUS_SYS12, &data_buff);
 	sprintf(string, "CUS_SYS12 = 0x%X" 
					"\t PJD_WIN_SEL %d"
					"\t CLKOUT_EN %d"
					"\t CLKOUT_DIV %d"
					"\n\n", data_buff, (data_buff & MASK_PJD_WIN_SEL)>>6, (data_buff & MASK_CLKOUT_EN)>>5, (data_buff & MASK_CLKOUT_DIV));
 	serialUSB_print_link(string);
	 
	/* Baseband Bank */
	serialUSB_print_link("\n\n::: Baseband Bank :::\n\n");
	
	marco_lectura_registros(CUS_PKT1, &data_buff);
 	sprintf(string, "CUS_PKT1 = 0x%X" 
					"\t RX_PREAM_SIZE %d"
					"\t PREAM_LENG_UNIT %d"
					"\t DATA_MODE %d"
					"\n\n", data_buff, (data_buff & MASK_RX_PREAM_SIZE)>>3, (data_buff & MASK_PREAM_LENG_UNIT)>>2, (data_buff & MASK_DATA_MODE));
 	serialUSB_print_link(string);

	marco_lectura_registros(CUS_PKT2, &data_buff);
	sprintf(string, "CUS_PKT2 = 0x%X\n\n", data_buff);
 	serialUSB_print_link(string);
	data_buff_long |= data_buff << 0;

	marco_lectura_registros(CUS_PKT3, &data_buff);
	sprintf(string, "CUS_PKT3 = 0x%X\n\n", data_buff);
	serialUSB_print_link(string);
	data_buff_long |= data_buff << 8;
	
 	sprintf(string, "\t TX_PREAM_SIZE %lu"
					"\n\n", data_buff_long);
 	serialUSB_print_link(string);
	 
	marco_lectura_registros(CUS_PKT4, &data_buff);
 	sprintf(string, "CUS_PKT4 = 0x%X" 
					"\t PREAM_VALUE 0x%X"
					"\n\n", data_buff, data_buff);
 	serialUSB_print_link(string);

	marco_lectura_registros(CUS_PKT5, &data_buff);
 	sprintf(string, "CUS_PKT5 = 0x%X" 
					"\t SYNC_TOL %d"
					"\t SYNC_SIZE %d"
					"\t SYNC_MAN_EN %d"
					"\n\n", data_buff, (data_buff & MASK_SYNC_TOL)>>4, (data_buff & MASK_SYNC_SIZE)>>1, (data_buff & MASK_SYNC_MAN_EN));
 	serialUSB_print_link(string);

	marco_lectura_registros(CUS_PKT6, &data_buff);
	sprintf(string, "CUS_PKT6 = 0x%X\n\n", data_buff);
 	serialUSB_print_link(string);

	marco_lectura_registros(CUS_PKT7, &data_buff);
	sprintf(string, "CUS_PKT7 = 0x%X\n\n", data_buff);
	serialUSB_print_link(string);

	marco_lectura_registros(CUS_PKT8, &data_buff);
	sprintf(string, "CUS_PKT8 = 0x%X\n\n", data_buff);
	serialUSB_print_link(string);

	marco_lectura_registros(CUS_PKT9, &data_buff);
	sprintf(string, "CUS_PKT9 = 0x%X\n\n", data_buff);
	serialUSB_print_link(string);

	marco_lectura_registros(CUS_PKT10, &data_buff);
	sprintf(string, "CUS_PKT10 = 0x%X\n\n", data_buff);
	serialUSB_print_link(string);
	
	marco_lectura_registros(CUS_PKT11, &data_buff);
	sprintf(string, "CUS_PKT11 = 0x%X\n\n", data_buff);
	serialUSB_print_link(string);
		
	marco_lectura_registros(CUS_PKT12, &data_buff);
	sprintf(string, "CUS_PKT12 = 0x%X\n\n", data_buff);
	serialUSB_print_link(string);
	
	marco_lectura_registros(CUS_PKT13, &data_buff);
	sprintf(string, "CUS_PKT13 = 0x%X\n\n", data_buff);
	serialUSB_print_link(string);
		
 	sprintf(string, "\t SYNC_VALUE 0x");
	serialUSB_print_link(string);

		marco_lectura_registros(CUS_PKT13, &data_buff);
		sprintf(string, "%X", data_buff);
		serialUSB_print_link(string);

		marco_lectura_registros(CUS_PKT12, &data_buff);
		sprintf(string, "%X", data_buff);
		serialUSB_print_link(string);
	
		marco_lectura_registros(CUS_PKT11, &data_buff);
		sprintf(string, "%X", data_buff);
		serialUSB_print_link(string);

		marco_lectura_registros(CUS_PKT10, &data_buff);
		sprintf(string, "%X", data_buff);
		serialUSB_print_link(string);

		marco_lectura_registros(CUS_PKT9, &data_buff);
		sprintf(string, "%X", data_buff);
		serialUSB_print_link(string);

		marco_lectura_registros(CUS_PKT8, &data_buff);
		sprintf(string, "%X", data_buff);
		serialUSB_print_link(string);

		marco_lectura_registros(CUS_PKT7, &data_buff);
		sprintf(string, "%X", data_buff);
		serialUSB_print_link(string);
	
		marco_lectura_registros(CUS_PKT6, &data_buff);
		sprintf(string, "%X\n\n", data_buff);
		serialUSB_print_link(string);

		marco_lectura_registros(CUS_PKT14, &data_buff);
		sprintf(string, "CUS_PKT14 = 0x%X"
						"\t PAYLOAD_LENG %d"
						"\t AUTO_ACK_EN %d"
						"\t NODE_LENG_POS_SEL %d"
						"\t PAYLOAD_BIT_ORDER %d"
						"\t PKT_TYPE %d"
						"\n\n", data_buff, (data_buff & MASK_PAYLOAD_LENG_10_8)>>4, (data_buff & MASK_AUTO_ACK_EN)>>3,
						  (data_buff & MASK_NODE_LENG_POS_SEL)>>2, (data_buff & MASK_PAYLOAD_BIT_ORDER)>>1, (data_buff & MASK_PKT_TYPE));
		serialUSB_print_link(string);

	marco_lectura_registros(CUS_PKT15, &data_buff);
		sprintf(string, "CUS_PKT15 = 0x%X"
						"\t PAYLOAD_LENG %d"
						"\n\n", data_buff, data_buff);
	serialUSB_print_link(string);

	marco_lectura_registros(CUS_PKT16, &data_buff);
	sprintf(string, "CUS_PKT16 = 0x%X"
					"\t NODE_FREE_EN %d"
					"\t NODE_ERR_MASK %d"
					"\t NODE_SIZE %d"
					"\t NODE_DET_MODE %d"
					"\n\n", data_buff, (data_buff & MASK_NODE_FREE_EN)>>5, (data_buff & MASK_NODE_ERR_MASK)>>4, (data_buff & MASK_NODE_SIZE)>>2,
							(data_buff & MASK_NODE_DET_MODE));
	serialUSB_print_link(string);

	marco_lectura_registros(CUS_PKT17, &data_buff);
	sprintf(string, "CUS_PKT17 = 0x%X\n\n", data_buff);
 	serialUSB_print_link(string);
	data_buff_long = 0;
	data_buff_long |= data_buff << 0;

	marco_lectura_registros(CUS_PKT18, &data_buff);
	sprintf(string, "CUS_PKT18 = 0x%X\n\n", data_buff);
	serialUSB_print_link(string);
	data_buff_long |= data_buff << 8;
	
	marco_lectura_registros(CUS_PKT19, &data_buff);
	sprintf(string, "CUS_PKT19 = 0x%X\n\n", data_buff);
	serialUSB_print_link(string);
	data_buff_long |= data_buff << 16;
	
	marco_lectura_registros(CUS_PKT20, &data_buff);
	sprintf(string, "CUS_PKT20 = 0x%X\n\n", data_buff);
	serialUSB_print_link(string);
	data_buff_long |= data_buff << 24;
	
 	sprintf(string, "\t NODE_VALUE %lu"
					"\n\n", data_buff_long);
 	serialUSB_print_link(string);
	
	marco_lectura_registros(CUS_PKT21, &data_buff);
	sprintf(string, "CUS_PKT21 = 0x%X"
					"\t FEC_TYPE %d"
					"\t FEC_EN %d"
					"\t CRC_BYTE_SWAP %d"
					"\t CRC_BIT_INV %d"
					"\t CRC_RANGE %d"
					"\t CRC_TYPE %d"
					"\t CRC_EN %d"
					"\n\n", data_buff, (data_buff & MASK_FEC_TYPE)>>7, (data_buff & MASK_FEC_EN)>>6, (data_buff & MASK_CRC_BYTE_SWAP)>>5,
							(data_buff & MASK_CRC_BIT_INV)>>4, (data_buff & MASK_CRC_RANGE)>>3, (data_buff & MASK_CRC_TYPE)>>1, (data_buff & MASK_CRC_EN));
	serialUSB_print_link(string);

	marco_lectura_registros(CUS_PKT22, &data_buff);
	sprintf(string, "CUS_PKT22 = 0x%X\n\n", data_buff);
 	serialUSB_print_link(string);
	data_buff_long = 0;
	data_buff_long |= data_buff << 0;

	marco_lectura_registros(CUS_PKT23, &data_buff);
	sprintf(string, "CUS_PKT23 = 0x%X\n\n", data_buff);
	serialUSB_print_link(string);
	data_buff_long |= data_buff << 8;
	
 	sprintf(string, "\t CRC_SEED 0x%X"
					"\n\n", data_buff_long);
 	serialUSB_print_link(string);

	marco_lectura_registros(CUS_PKT24, &data_buff);
	sprintf(string, "CUS_PKT24 = 0x%X"
					"\t CRC_BIT_ORDER %d"
					"\t WHITEN_SEED %d"
					"\t WHITEN_SEED_TYPE %d"
					"\t WHITEN_TYPE %d"
					"\t WHITEN_EN %d"
					"\t MANCH_TYPE %d"
					"\t MANCH_EN %d"
					"\n\n", data_buff, (data_buff & MASK_CRC_BIT_ORDER)>>7, (data_buff & MASK_WHITEN_SEED_8_8)>>6, (data_buff & MASK_WHITEN_SEED_TYPE)>>5,
							(data_buff & MASK_WHITEN_TYPE)>>3, (data_buff & MASK_WHITEN_EN)>>2, (data_buff & MASK_MANCH_TYPE)>>1, (data_buff & MASK_MANCH_EN));
	serialUSB_print_link(string);

	marco_lectura_registros(CUS_PKT25, &data_buff);
	sprintf(string, "CUS_PKT25 = 0x%X"
						"\t WHITEN_SEED %d"
						"\n\n", data_buff, data_buff);
	serialUSB_print_link(string);

	marco_lectura_registros(CUS_PKT26, &data_buff);
	sprintf(string, "CUS_PKT26 = 0x%X"
						"\t TX_PREFIX_TYPE %d"
						"\n\n", data_buff, data_buff);
	serialUSB_print_link(string);

	marco_lectura_registros(CUS_PKT27, &data_buff);
	sprintf(string, "CUS_PKT27 = 0x%X"
						"\t TX_PKT_NUM %d"
						"\n\n", data_buff, data_buff);
	serialUSB_print_link(string);
	
	marco_lectura_registros(CUS_PKT28, &data_buff);
	sprintf(string, "CUS_PKT28 = 0x%X"
						"\t TX_PKT_GAP %d"
						"\n\n", data_buff, data_buff);
	serialUSB_print_link(string);
	
	marco_lectura_registros(CUS_PKT29, &data_buff);
	sprintf(string, "CUS_PKT29 = 0x%X"
					"\t FIFO_AUTO_RES_EN %d"
					"\t FIFO_TH %d"
					"\n\n", data_buff, (data_buff & MASK_FIFO_AUTO_RES_EN)>>7, (data_buff & MASK_FIFO_TH));
	serialUSB_print_link(string);
	
	/* Control Bank 1 */
	serialUSB_print_link("\n\n::: Control Bank 1 :::\n\n");
	
	marco_lectura_registros(CUS_MODE_CTL, &data_buff);
	sprintf(string, "CUS_MODE_CTL = 0x%X"
					"\t CHIP_MODE_SWT %d"
					"\n\n", data_buff, data_buff);
	serialUSB_print_link(string);
	
	marco_lectura_registros(CUS_MODE_STA, &data_buff);
	sprintf(string, "CUS_MODE_STA = 0x%X"
					"\t RSTN_IN_EN %d"
					"\t CFG_RETAIN %d"
					"\t CHIP_MODE_STA %d"
					"\n\n", data_buff, (data_buff & MASK_RSTN_IN_EN)>>5,(data_buff & MASK_CFG_RETAIN)>>4, (data_buff & MASK_CHIP_MODE_STA));
	serialUSB_print_link(string);
	
	marco_lectura_registros(CUS_EN_CTL, &data_buff);
	sprintf(string, "CUS_EN_CTL = 0x%X"
					"\t LOCKING_EN %d"
					"\n\n", data_buff, (data_buff & MASK_LOCKING_EN)>>5);
	serialUSB_print_link(string);
	
	marco_lectura_registros(CUS_FREQ_CHNL, &data_buff);
	sprintf(string, "CUS_FREQ_CHNL = 0x%X"
					"\t FH_CHANNEL %d"
					"\n\n", data_buff, data_buff);
	serialUSB_print_link(string);
	
	marco_lectura_registros(CUS_FREQ_OFS, &data_buff);
	sprintf(string, "CUS_FREQ_OFS = 0x%X"
				"\t FH_OFFSET %d"
				"\n\n", data_buff, data_buff);
	serialUSB_print_link(string);
	
	marco_lectura_registros(CUS_IO_SEL, &data_buff);
	sprintf(string, "CUS_IO_SEL = 0x%X"
					"\t GPIO3_SEL %d"
					"\t GPIO2_SEL %d"
					"\t GPIO1_SEL %d"
					"\n\n", data_buff, (data_buff & MASK_GPIO3_SEL)>>4, (data_buff & MASK_GPIO2_SEL)>>2, (data_buff & MASK_GPIO1_SEL));
	serialUSB_print_link(string);
	
	marco_lectura_registros(CUS_INT1_CTL, &data_buff);
	sprintf(string, "CUS_INT1_CTL = 0x%X"
					"\t RF_SWT1_EN %d"
					"\t RF_SWT2_EN %d"
					"\t INT_POLAR %d"
					"\t INT1_SEL %d"
					"\n\n", data_buff, (data_buff & MASK_RF_SWT1_EN)>>4, (data_buff & MASK_RF_SWT2_EN)>>2, (data_buff & MASK_INT_POLAR)>>2,
							(data_buff & MASK_INT1_SEL));
	serialUSB_print_link(string);
	
	marco_lectura_registros(CUS_INT2_CTL, &data_buff);
	sprintf(string, "CUS_INT2_CTL = 0x%X"
					"\t LFOSC_OUT_EN %d"
					"\t TX_DIN_INV %d"
					"\t INT2_SEL %d"
					"\n\n", data_buff, (data_buff & MASK_LFOSC_OUT_EN)>>4, (data_buff & MASK_TX_DIN_INV)>>2, (data_buff & MASK_INT2_SEL));
	serialUSB_print_link(string);

	marco_lectura_registros(CUS_INT_EN, &data_buff);
	sprintf(string, "CUS_INT_EN = 0x%X"
					"\t SL_TMO_EN %d"
					"\t RX_TMO_EN %d"
					"\t TX_DONE_EN %d"
					"\t PREAM_OK_EN %d"
					"\t SYNC_OK_EN %d"
					"\t NODE_OK_EN %d"
					"\t CRC_OK_EN %d"
					"\t PKT_DONE_EN %d"
					"\n\n", data_buff, (data_buff & MASK_SL_TMO_EN)>>7, (data_buff & MASK_RX_TMO_EN)>>6, (data_buff & MASK_TX_DONE_EN)>>5,
							(data_buff & MASK_PREAM_OK_EN)>>4, (data_buff & MASK_SYNC_OK_EN)>>3, (data_buff & MASK_NODE_OK_EN)>>2,
							(data_buff & MASK_CRC_OK_EN)>>1,  (data_buff & MASK_PKT_DONE_EN));
	serialUSB_print_link(string);

	marco_lectura_registros(CUS_FIFO_CTL, &data_buff);
	sprintf(string, "CUS_FIFO_CTL = 0x%X"
					"\t TX_DIN_EN %d"
					"\t TX_DIN_SEL %d"
					"\t FIFO_AUTO_CLR_DIS %d"
					"\t FIFO_TX_RD_EN %d"
					"\t FIFO_RX_TX_SEL %d"
					"\t FIFO_MERGE_EN %d"
					"\t SPI_FIFO_RD_WR_SEL %d"
					"\n\n", data_buff, (data_buff & MASK_TX_DIN_EN)>>7, (data_buff & MASK_TX_DIN_SEL)>>5,
							(data_buff & MASK_FIFO_AUTO_CLR_DIS)>>4, (data_buff & MASK_FIFO_TX_RD_EN)>>3, (data_buff & MASK_FIFO_RX_TX_SEL)>>2,
							(data_buff & MASK_FIFO_MERGE_EN)>>1,  (data_buff & MASK_SPI_FIFO_RD_WR_SEL));
	serialUSB_print_link(string);

}
#endif /* PRUEBA_CMT2300A */
